### ISSUE TITLE
Can´t launch getdown in virtual machine with 1 CPU

### ISSUE THREAD

**Issue by ThomasG-AI** [threerings/getdown#161]
Hi,

in commit [0f5622df722ee695d06fb889df679291faa54f9d](https://github.com/threerings/getdown/commit/0f5622df722ee695d06fb889df679291faa54f9d#diff-2f646cf5a4638e5a222c620f41ee9f56) you added a "-1" to the threadPoolSize() method inside die SysPros-Class. 

This leads to an ArrayIndexOutOfBoundsException when running getdown inside a virtual machine with only one cpu. Was there a particular reason why the "-1" was added since it was not included the commit before?

Stacktrace:

> 2018/11/19 15:37:15:734 WARNUNG getdown() failed. [java.lang.IllegalArgumentException=<toString() failure: java.lang.ArrayIndexOutOfBoundsException: 1>]
java.lang.IllegalArgumentException
	at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1314)
	at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1202)
	at java.util.concurrent.Executors.newFixedThreadPool(Executors.java:89)
	at com.threerings.getdown.data.Application.verifyResources(Application.java:1227)
	at com.threerings.getdown.launcher.Getdown.getdown(Unknown Source)
	at com.threerings.getdown.launcher.Getdown.run(Unknown Source)
2018/11/19 15:37:15:740 INFORMATION Releasing lock

Greetings
ThomasG

**Comment by samskivert** [comment]
I have pushed a fix for this. The reason for the `-1` is that using _all_ of the processors on a machine was leading to resource starvation and thrashing for some users. It is generally considered to be "good behavior" to leave at least one process for "foreground" tasks when creating background thread pools.
