### ISSUE TITLE
Getdownlauncher 1.8 Application class is missing in launcher.jar 

### ISSUE THREAD

**Issue by thomasX** [threerings/getdown#165]
when we star getdown with Windows everything is okay, but when we start it with linux we get the following error: 
`2018/11/26 18:55:58:362 INFO Able to lock for updates: true
2018/11/26 18:55:58:530 INFO Verifying application: http://pps.felder.intranet/ferps2j8/getdown/ferps2g/
2018/11/26 18:55:58:530 INFO Version: -1
2018/11/26 18:55:58:530 INFO Class: at.felder.FERPS.CLIENT.Installer
2018/11/26 18:55:58:538 INFO Dropping status 'm.validating'.
2018/11/26 18:55:58:563 INFO Attempting to refetch 'digest.txt' from 'http://pps.felder.intranet/ferps2j8/getdown/ferps2g/digest.txt'.
2018/11/26 18:55:58:600 INFO No signing certs, not verifying digest.txt [path=digest.txt]
2018/11/26 18:55:58:601 INFO Attempting to refetch 'digest2.txt' from 'http://pps.felder.intranet/ferps2j8/getdown/ferps2g/digest2.txt'.
2018/11/26 18:55:58:602 INFO No signing certs, not verifying digest.txt [path=digest2.txt]
2018/11/26 18:55:58:612 WARNING getdown() failed. [java.lang.IllegalArgumentException=<toString() failure: java.lang.ArrayIndexOutOfBoundsException: 1>]
java.lang.IllegalArgumentException
        at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1314)
        at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1202)
        at java.util.concurrent.Executors.newFixedThreadPool(Executors.java:89)
        at com.threerings.getdown.data.Application.verifyResources(Unknown Source)
        at com.threerings.getdown.launcher.Getdown.getdown(Unknown Source)
        at com.threerings.getdown.launcher.Getdown.run(Unknown Source)
2018/11/26 18:55:58:621 INFO Releasing lock
`

**Comment by samskivert** [comment]
Will be fixed in 1.8.1 release.
