### ISSUE TITLE
[1.8.6] versioned mode, problem with apply patch

### ISSUE THREAD

**Issue by 5force** [threerings/getdown#230]
Hi
After patch file has been downloaded, it can't be applied to original jar. Original jar became zero sized.
launcher.log
`2019/06/23 13:06:28:672 INFO Getdown starting [version=1.8.6, built=2019-06-04 15:27]
2019/06/23 13:06:28:672 INFO Checking whether we need to use a proxy...
2019/06/23 13:06:28:783 INFO Attempting to fetch without proxy: http://my_update_url/OldVersion/getdown.txt
2019/06/23 13:06:29:075 INFO No proxy appears to be needed.
2019/06/23 13:06:29:085 INFO Able to lock for updates: true
2019/06/23 13:06:29:085 INFO Verifying application: http://my_update_url/OldVersion/
2019/06/23 13:06:29:086 INFO Version: OldVersion
2019/06/23 13:06:29:086 INFO Class: my_class.Launcher
2019/06/23 13:06:29:269 INFO Application requires update.
2019/06/23 13:06:29:426 INFO Downloading 1 resources [totalBytes=18589, maxConcurrent=1]
2019/06/23 13:06:29:585 INFO Downloading resource [url=http://my_update_url/NewVersion/patchOldVersion.dat, size=18589]
2019/06/23 13:06:29:663 INFO - ./patchOldVersion.dat_new
2019/06/23 13:06:29:671 INFO Patching my_jar.jar...
Exception in thread "Getdown" java.lang.AssertionError: Unsupported source file './my_jar.jar.old'. Not a .jar or .zip?
	at com.threerings.getdown.tools.JarDiffPatcher.makeOutputStream(Unknown Source)
	at com.threerings.getdown.tools.JarDiffPatcher.patchJar(Unknown Source)
	at com.threerings.getdown.tools.Patcher.patchFile(Unknown Source)
	at com.threerings.getdown.tools.Patcher.patch(Unknown Source)
	at com.threerings.getdown.launcher.Getdown.update(Unknown Source)
	at com.threerings.getdown.launcher.Getdown.getdown(Unknown Source)
	at com.threerings.getdown.launcher.Getdown.run(Unknown Source)
	at com.threerings.getdown.launcher.a.run(Unknown Source)
`
Original jar was created with maven-shade-plugin

**Comment by 5force** [comment]
Seems JarDiffPatcher.makeOutputStream does not understand file extension .jar.old
