### ISSUE TITLE
Release documentation

### ISSUE THREAD

**Issue by motofix** [threerings/getdown#31]
Would it be possible to have a little documentation, and maybe some configuration options in the Maven `pom.xml`, to be able to release a fork in an internal Maven repo while waiting for pull-requests or official release to comes out?
Today some plugin prevent a standard Maven release to take place out-of-the-box, and if removed some of the jar content is obviously missing 

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/samskivert/util/StringUtil
        at com.threerings.getdown.launcher.GetdownApp.main(GetdownApp.java:44)
Caused by: java.lang.ClassNotFoundException: com.samskivert.util.StringUtil
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 1 more
```

**Comment by motofix** [comment]
For information, in order to be able to release, we've made the following changes in the ```pom.xml```:
* Change the parent
* Change the version
* Change scm connection
* Remove ```nexus-staging-maven-plugin```
* Remove ```release-sign-artifacts``` profile

**Comment by samskivert** [comment]
I'm happy to support making local releases, but I don't know how that works. What Maven commands do you use to make a local release? Where does the local release go? To a locally operated Artifactory repository?

**Comment by motofix** [comment]
We are executing a standard Maven release:
```mvn release:prepare release:perform```
The release is uploaded to our internal enterprise Maven repo.
